const templateData = {
  categories: [
    {
      id: "personal",
      name: "Personal & Life",
      icon: "🤔",
      description: "Life goals, productivity, and personal decisions",
    },
    {
      id: "tech",
      name: "Tech & Digital",
      icon: "💻",
      description: "Programming, gadgets, and AI tools",
    },
    {
      id: "entertainment",
      name: "Entertainment",
      icon: "🎬",
      description: "Movies, TV shows, music, and games",
    },
    {
      id: "food",
      name: "Food & Beverage",
      icon: "🍕",
      description: "Cuisines, drinks, and culinary favorites",
    },
    {
      id: "work",
      name: "Work & Career",
      icon: "📊",
      description:
        "Professional growth, management styles, and workplace preferences",
    },
    {
      id: "travel",
      name: "Travel & Places",
      icon: "🌍",
      description: "Cities, destinations, and bucket-list adventures",
    },
    {
      id: "fitness",
      name: "Health & Fitness",
      icon: "💪",
      description: "Exercises, routines, and wellness priorities",
    },
    {
      id: "education",
      name: "Learning & Education",
      icon: "📚",
      description: "Study methods, school subjects, and skill development",
    },
    {
      id: "hobby",
      name: "Hobbies & Interests",
      icon: "🎨",
      description:
        "Creative outlets, leisure activities, and personal passions",
    },
    {
      id: "music",
      name: "Music",
      icon: "🎵",
      description: "Genres, artists, and musical preferences",
    },
    {
      id: "gaming",
      name: "Gaming",
      icon: "🕹️",
      description: "Videogames, consoles, and game genres",
    },
    {
      id: "sports",
      name: "Sports",
      icon: "🏅",
      description: "Sports, teams, and athletic rankings",
    },
    {
      id: "blank",
      name: "Start Blank",
      icon: "✨",
      description: "Begin with your own empty list",
    },
  ],

  templates: [
    // ======================
    // PERSONAL & LIFE
    // ======================
    {
      id: "life-priorities",
      name: "Life Priorities",
      category: "personal",
      description: "Rank what matters most, from career to family.",
      items: [
        "Family",
        "Health",
        "Happiness",
        "Financial Stability",
        "Career",
        "Social Connections",
        "Purpose",
        "Learning",
        "Spirituality",
        "Creation",
        "Adventure",
      ],
    },
    {
      id: "partner-traits",
      name: "Traits in an Ideal Partner",
      category: "personal",
      description: "What qualities matter most to you when choosing a partner?",
      items: [
        "Physical Attractiveness",
        "Emotional Intelligence",
        "Sense of Humour",
        "Kindness",
        "Sexual Compatibility",
        "Ambition",
        "From A Good Family",
        "Life Stability",
        "Financial Wellbeing",
        "Communication Skills",
        "Loyalty",
        "Shared Values",
        "Compatibility with Lifestyle",
        "Intellectual Curiosity",
      ],
    },
    {
      id: "productivity-methods",
      name: "Productivity Methods",
      category: "personal",
      description: "Which techniques work best for you?",
      items: [
        "Pomodoro Technique",
        "Getting Things Done",
        "Time Blocking",
        "Eisenhower Matrix",
        "Kanban Boards",
        "Deep Work",
        "Habit Stacking",
        "Energy Management",
      ],
    },
    {
      id: "core-values",
      name: "Core Personal Values",
      category: "personal",
      description: "What principles guide your life?",
      items: [
        "Integrity",
        "Growth",
        "Compassion",
        "Ambition",
        "Freedom",
        "Discipline",
        "Balance",
        "Creativity",
        "Connection",
        "Resilience",
      ],
    },
    {
      id: "self-care-activities",
      name: "Self-Care Activities",
      category: "personal",
      description: "Prioritize what recharges you mentally and emotionally.",
      items: [
        "Reading",
        "Baths",
        "Nature Walks",
        "Meditation",
        "Journaling",
        "Music",
        "Time Alone",
        "Therapy",
        "Movie Night",
        "Massage",
      ],
    },

    // ======================
    // TECH
    // ======================
    {
      id: "smartphone-brands",
      name: "Smartphone Brands",
      category: "tech",
      description: "Which phone manufacturer comes out on top?",
      items: [
        "Apple iPhone",
        "Samsung Galaxy",
        "Google Pixel",
        "OnePlus",
        "Xiaomi",
        "Nothing Phone",
      ],
    },
    {
      id: "programming-languages",
      name: "Programming Languages",
      category: "tech",
      description: "The ultimate showdown of coding languages.",
      items: [
        "JavaScript",
        "Python",
        "TypeScript",
        "Java",
        "C++",
        "Rust",
        "Go",
        "Swift",
        "Kotlin",
        "PHP",
      ],
    },
    {
      id: "cloud-providers",
      name: "Cloud Providers",
      category: "tech",
      description: "Rank the giants of the cloud ecosystem.",
      items: [
        "AWS",
        "Google Cloud",
        "Microsoft Azure",
        "DigitalOcean",
        "Vercel",
        "Netlify",
        "Oracle Cloud",
        "IBM Cloud",
      ],
    },
    {
      id: "ai-tools",
      name: "AI Tools & Assistants",
      category: "tech",
      description: "Which AI tools do you find the most useful?",
      items: [
        "ChatGPT",
        "Claude",
        "Copilot",
        "Midjourney",
        "Stable Diffusion",
        "Perplexity",
        "Cursor",
        "Replit Ghostwriter",
      ],
    },

    // ======================
    // ENTERTAINMENT
    // ======================
    {
      id: "marvel-movies",
      name: "Marvel Movies (Top 8)",
      category: "entertainment",
      description: "Rank the best of the MCU.",
      items: [
        "Avengers: Endgame",
        "Iron Man",
        "The Avengers",
        "Thor: Ragnarok",
        "Guardians of the Galaxy",
        "Black Panther",
        "Spider-Man: Homecoming",
        "Doctor Strange",
      ],
    },
    {
      id: "streaming-platforms",
      name: "Streaming Services",
      category: "entertainment",
      description: "Which streaming platform is the best value?",
      items: [
        "Netflix",
        "Disney+",
        "HBO Max",
        "Amazon Prime Video",
        "Apple TV+",
        "Hulu",
        "YouTube Premium",
      ],
    },
    {
      id: "movie-genres",
      name: "Movie Genres",
      category: "entertainment",
      description: "Pick your favorite genres.",
      items: [
        "Action",
        "Comedy",
        "Drama",
        "Sci-Fi",
        "Romance",
        "Thriller",
        "Horror",
        "Animation",
        "Fantasy",
        "Documentary",
      ],
    },
    {
      id: "tv-shows",
      name: "Top TV Shows",
      category: "entertainment",
      description: "Your priority watchlist.",
      items: [
        "Breaking Bad",
        "Game of Thrones",
        "Stranger Things",
        "The Office",
        "The Mandalorian",
        "Narcos",
        "Sherlock",
        "Succession",
      ],
    },

    // ======================
    // FOOD
    // ======================
    {
      id: "world-cuisines",
      name: "World Cuisines",
      category: "food",
      description: "Find your favorite international food style.",
      items: [
        "Italian",
        "Japanese",
        "Mexican",
        "Indian",
        "Thai",
        "French",
        "Chinese",
        "Mediterranean",
      ],
    },
    {
      id: "coffee-types",
      name: "Coffee Drinks",
      category: "food",
      description: "The definitive ranking of coffee preparations.",
      items: [
        "Espresso",
        "Cappuccino",
        "Latte",
        "Americano",
        "Mocha",
        "Cold Brew",
        "French Press",
        "Flat White",
      ],
    },
    {
      id: "favorite-fruits",
      name: "Favorite Fruits",
      category: "food",
      description: "Rank your fruit preferences.",
      items: [
        "Mango",
        "Strawberry",
        "Banana",
        "Apple",
        "Blueberry",
        "Orange",
        "Pineapple",
        "Watermelon",
        "Grapes",
      ],
    },
    {
      id: "fast-food-chains",
      name: "Fast Food Chains",
      category: "food",
      description: "Where do you go when you're hungry?",
      items: [
        "McDonalds",
        "KFC",
        "Taco Bell",
        "Burger King",
        "Pizza Hut",
        "Subway",
        "Chipotle",
        "Wendys",
      ],
    },

    // ======================
    // WORK
    // ======================
    {
      id: "leadership-styles",
      name: "Leadership Styles",
      category: "work",
      description: "Compare leadership approaches.",
      items: [
        "Democratic",
        "Autocratic",
        "Laissez-Faire",
        "Transformational",
        "Transactional",
        "Servant Leadership",
        "Visionary",
        "Coaching",
      ],
    },
    {
      id: "productivity-tools",
      name: "Productivity Tools",
      category: "work",
      description: "Which tools actually boost your work output?",
      items: [
        "Notion",
        "Google Workspace",
        "Microsoft Office",
        "Trello",
        "Asana",
        "Slack",
        "Todoist",
        "Obsidian",
      ],
    },
    {
      id: "career-goals",
      name: "Career Goals",
      category: "work",
      description: "What professional milestones matter most?",
      items: [
        "Salary Growth",
        "Work-Life Balance",
        "Advancing to Leadership",
        "Skills Development",
        "Impactful Work",
        "Remote Work",
        "Entrepreneurship",
      ],
    },
    {
      id: "meeting-types",
      name: "Types of Meetings",
      category: "work",
      description: "Rank meeting formats by usefulness.",
      items: [
        "One-on-One",
        "Team Sync",
        "Stand-Up",
        "Brainstorm",
        "Planning Session",
        "Review Meeting",
        "Retrospective",
        "Status Update",
      ],
    },

    // ======================
    // TRAVEL
    // ======================
    {
      id: "dream-destinations",
      name: "Dream Destinations",
      category: "travel",
      description: "Rank your bucket-list travel goals.",
      items: [
        "Japan",
        "Iceland",
        "New Zealand",
        "Greece",
        "Italy",
        "Thailand",
        "Peru",
        "Norway",
      ],
    },
    {
      id: "transportation-methods",
      name: "Travel Transport Modes",
      category: "travel",
      description: "Which way do you prefer to get around?",
      items: [
        "Train",
        "Plane",
        "Bus",
        "Car",
        "Motorbike",
        "Boat",
        "Bicycle",
        "Walking",
      ],
    },
    {
      id: "travel-activities",
      name: "Travel Activities",
      category: "travel",
      description: "What do you want to do on trips?",
      items: [
        "Sightseeing",
        "Hiking",
        "Food Tours",
        "Museums",
        "Beach Relaxing",
        "Shopping",
        "Photography",
        "Nightlife",
      ],
    },
    {
      id: "world-cities",
      name: "World Cities",
      category: "travel",
      description: "Your personal favorite major cities.",
      items: [
        "Tokyo",
        "New York",
        "Paris",
        "London",
        "Bangkok",
        "Barcelona",
        "Singapore",
        "Dubai",
        "Seoul",
        "Rome",
      ],
    },

    // ======================
    // FITNESS
    // ======================
    {
      id: "cardio-exercises",
      name: "Cardio Exercises",
      category: "fitness",
      description: "Which cardio methods do you enjoy the most?",
      items: [
        "Running",
        "Cycling",
        "Jump Rope",
        "Swimming",
        "Rowing",
        "HIIT",
        "Elliptical",
        "Boxing",
      ],
    },
    {
      id: "wellness-habits",
      name: "Wellness Habits",
      category: "fitness",
      description: "Prioritize what keeps you balanced.",
      items: [
        "Meditation",
        "Sleep",
        "Hydration",
        "Daily Stretching",
        "Strength Training",
        "Sunlight Exposure",
        "Social Time",
        "Healthy Eating",
      ],
    },
    {
      id: "strength-exercises",
      name: "Strength Exercises",
      category: "fitness",
      description: "Rank your favorite strength training moves.",
      items: [
        "Squat",
        "Deadlift",
        "Bench Press",
        "Pull-Up",
        "Push-Up",
        "Lunge",
        "Overhead Press",
        "Rows",
      ],
    },

    // ======================
    // EDUCATION
    // ======================
    {
      id: "study-methods",
      name: "Study Methods",
      category: "education",
      description: "Which techniques help you learn most effectively?",
      items: [
        "Spaced Repetition",
        "Mind Maps",
        "Flashcards",
        "Note Summaries",
        "Practice Exams",
        "Teaching Others",
        "Active Recall",
        "Pomodoro Sessions",
      ],
    },
    {
      id: "school-subjects",
      name: "School Subjects",
      category: "education",
      description: "Rank subjects by interest or difficulty.",
      items: [
        "Math",
        "Science",
        "History",
        "Geography",
        "English",
        "Art",
        "Computer Science",
        "Physical Education",
      ],
    },
    {
      id: "languages-to-learn",
      name: "Languages to Learn",
      category: "education",
      description: "Which languages do you want to study?",
      items: [
        "Spanish",
        "French",
        "Mandarin",
        "Japanese",
        "Korean",
        "Arabic",
        "German",
        "Italian",
      ],
    },

    // ======================
    // HOBBIES
    // ======================
    {
      id: "hobbies",
      name: "Hobby Interests",
      category: "hobby",
      description: "Organize your creative passions.",
      items: [
        "Drawing",
        "Singing",
        "Playing Instruments",
        "Photography",
        "Reading",
        "Cooking",
        "Gardening",
        "Hiking",
        "Writing",
        "Board Games",
      ],
    },

    // ======================
    // MUSIC
    // ======================
    {
      id: "music-genres",
      name: "Music Genres",
      category: "music",
      description: "Rank your go-to genres.",
      items: [
        "Pop",
        "Rock",
        "Hip-Hop",
        "R&B",
        "Jazz",
        "Classical",
        "Electronic",
        "Indie",
        "Metal",
      ],
    },

    // ======================
    // GAMING
    // ======================
    {
      id: "game-genres",
      name: "Game Genres",
      category: "gaming",
      description: "What kind of games do you love?",
      items: [
        "RPG",
        "Action",
        "Adventure",
        "Shooter",
        "Puzzle",
        "Strategy",
        "Simulation",
        "Platformer",
      ],
    },
    {
      id: "gaming-platforms",
      name: "Gaming Platforms",
      category: "gaming",
      description: "Rank the systems you play on.",
      items: ["PC", "PlayStation", "Xbox", "Nintendo Switch", "Mobile", "VR"],
    },

    // ======================
    // SPORTS
    // ======================
    {
      id: "sports",
      name: "Sports Types",
      category: "sports",
      description: "Which sports are the most exciting?",
      items: [
        "Football",
        "Basketball",
        "Soccer",
        "Tennis",
        "Baseball",
        "Swimming",
        "Cycling",
        "Running",
        "Martial Arts",
      ],
    },

    // ======================
    // BLANK
    // ======================
    {
      id: "blank",
      name: "Blank List",
      category: "blank",
      description: "Start fresh with an empty list.",
      items: [],
    },
  ],
};
